import { Karla } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "@/components/Footer";


const karla = Karla({
  subsets: ["latin"],
  variable: "--font-geist-mono",
  weight: ["400", "700"],
}); 


export const metadata = {
  title: "Kamaan",
  description: "Generated by synwave",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${karla.className} antialiased `}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
